import { useCopy } from '@/src/i18n';

export const RESCUE_DETAILS_COPY = {
  vi: {
    retryError: 'Không thể tìm lại đội cứu hộ.',
    loadError: 'Không thể tải yêu cầu này.',
    back: 'Quay lại',
    pickupMarker: 'Vị trí cứu hộ',
    destinationMarker: 'Điểm giao xe',
    provider: 'Cứu hộ viên',
    contact: 'Liên hệ',
    roadRoute: 'Tuyến đường xe máy',
    noRoute: 'Chưa có tuyến đường',
    landmark: 'Điểm nhận biết',
    destination: 'Điểm giao xe',
    team: 'Đội đã xác minh',
    vehicle: 'Phương tiện nhận diện',
    initialEta: 'ETA ban đầu',
    aboutMinutes: 'Khoảng {value} phút',
    road: 'Đường bộ',
    fullscreen: 'Mở bản đồ toàn màn hình',
    routingWarning:
      'Dịch vụ định tuyến không trả đường hợp lệ. Ứng dụng không thay bằng đường chim bay; điều phối viên cần tìm lại khi tuyến đường hoạt động.',
    noProviderTitle: 'Hiện chưa có đội nhận ca',
    noProviderBody:
      'Hệ thống đã dừng tìm, không hiển thị chờ vô thời hạn. Liên hệ điều phối nếu bạn cần phương án khác.',
    callDispatch: 'Gọi điều phối',
    requestDispatchSupport: 'Yêu cầu điều phối hỗ trợ',
    supportRequested: 'Đã gửi yêu cầu. Điều phối viên sẽ kiểm tra ca này.',
    supportError: 'Không thể gửi yêu cầu hỗ trợ.',
    dispatcher: 'Điều phối viên',
    retry: 'Tìm lại đội phù hợp',
    gpsStaleTitle: 'Vị trí cứu hộ viên đã cũ',
    gpsStaleBody: 'Tuyến đường và ETA tạm dừng cho đến khi thiết bị của cứu hộ viên gửi GPS mới.',
    dispatchRequiredTitle: 'Điều phối viên đang xử lý lại ca',
    dispatchRequiredBody: 'Đội trước không thể tiếp tục. Yêu cầu của bạn vẫn được giữ và chưa bị hủy.',
    attentionRequired: 'Ca này có cảnh báo vận hành cần kiểm tra',
    progress: 'Tiến trình',
    callProvider: 'Gọi cứu hộ viên theo số',
    contactLabel: 'Số liên hệ trong ca',
    contactPrivacy: 'Số công việc đã được đơn vị vận hành xác minh',
    call: 'Gọi',
    tracking: {
      idle: 'Theo dõi vị trí chưa hoạt động.',
      requesting: 'Đang xin quyền vị trí…',
      tracking: 'Đang chia sẻ vị trí cho khách của ca này.',
      denied: 'Không có quyền vị trí; bạn không thể xử lý ca an toàn.',
      error: 'Mất kết nối vị trí. Hệ thống sẽ thử lại khi GPS cập nhật.',
    },
    expoTracking: 'Expo Go chỉ theo dõi khi màn hình này đang mở.',
    quote: 'Báo giá',
    transport: 'Vận chuyển xe',
    repair: 'Sửa chữa',
    quotePending: 'Chờ duyệt',
    quoteApproved: 'Đã duyệt',
    quoteRejected: 'Đã từ chối',
    quoteSuperseded: 'Đã thay thế',
    actionError: 'Không thể thực hiện thao tác.',
    cancelTitle: 'Hủy yêu cầu?',
    cancelBody: 'Chọn lý do để điều phối hiểu đúng tình huống. Thao tác sẽ được ghi vào lịch sử.',
    no: 'Không',
    cancel: 'Hủy yêu cầu',
    chooseCancelReason: 'Lý do hủy',
    cancelReasonRequired: 'Hãy chọn một lý do hủy.',
    otherReasonRequired: 'Hãy mô tả lý do bằng ít nhất 5 ký tự.',
    cancelNote: 'Mô tả thêm (không bắt buộc)',
    cancelOtherNote: 'Mô tả lý do',
    lateCancelWarning:
      'Đội cứu hộ đã xuất phát. Lần hủy này được ghi nhận là hủy muộn; nhiều lần hủy muộn có thể tạm giới hạn tạo ca mới.',
    arrivalDisputeWarning:
      'Đội cứu hộ đã báo đến nơi. Nếu bạn chưa thấy họ, lần hủy này sẽ được chuyển thành trường hợp cần điều phối kiểm tra.',
    cancelAfterArrivalTitle: 'Cần dừng ca sau khi đã xác nhận đội đến?',
    cancelAfterArrivalBody:
      'Bạn không thể tự hủy ở giai đoạn đang xử lý. Hãy gọi điều phối để bảo vệ cả khách và đội cứu hộ, đồng thời lưu đúng diễn biến ca.',
    cancellationRecorded: 'Thông tin hủy',
    operationalCancellation: 'Ca đã được dừng bởi đội cứu hộ hoặc điều phối.',
    lateCancellationRecorded: 'Đã ghi nhận hủy muộn',
    gpsNearRecorded: 'GPS gần điểm cứu hộ khi hủy',
    reasonLabels: {
      issue_resolved: 'Xe đã tự hoạt động lại / không còn cần hỗ trợ',
      changed_mind: 'Đổi ý hoặc đã chọn phương án khác',
      wrong_location: 'Chọn sai vị trí',
      duplicate_request: 'Gửi trùng yêu cầu',
      provider_not_present: 'Chưa thấy đội cứu hộ tại điểm hẹn',
      provider_unavailable: 'Đội cứu hộ không thể tiếp tục',
      safety_issue: 'Có vấn đề an toàn',
      customer_unreachable: 'Không liên lạc được với khách',
      duplicate_or_fraud: 'Yêu cầu trùng hoặc có dấu hiệu bất thường',
      other: 'Lý do khác',
    },
    confirmArrival: 'Xác nhận cứu hộ viên đã đến',
    rejectArrival: 'Chưa thấy cứu hộ viên',
    approveQuote: 'Đồng ý báo giá',
    rejectQuote: 'Từ chối báo giá',
    chooseDestination: 'Chọn điểm giao xe',
    destinationBeforeQuote: 'Báo giá vận chuyển cần điểm giao xe trước khi bạn có thể duyệt.',
    confirmCompletion: 'Xác nhận đã hoàn tất',
    incomplete: 'Công việc chưa hoàn tất',
    feedbackTitle: 'Cho biết điều gì chưa đúng',
    feedbackReasonRequired: 'Hãy chọn lý do trước khi gửi.',
    feedbackNote: 'Mô tả thêm',
    sendFeedback: 'Gửi và yêu cầu xử lý lại',
    closeFeedback: 'Quay lại',
    feedbackReasons: {
      provider_not_visible: 'Chưa thấy cứu hộ viên tại điểm hẹn',
      wrong_meeting_point: 'Cứu hộ viên đang ở sai điểm',
      cannot_contact_provider: 'Không liên lạc được với cứu hộ viên',
      issue_persists: 'Xe vẫn còn lỗi',
      work_not_as_agreed: 'Công việc không đúng nội dung đã thống nhất',
      destination_not_reached: 'Xe chưa đến đúng điểm giao',
      other: 'Lý do khác',
    },
    stateError: 'Không thể cập nhật trạng thái.',
    quoteInvalid: 'Nhập nội dung và số tiền báo giá hợp lệ.',
    quoteError: 'Không thể gửi báo giá.',
    startTrip: 'Bắt đầu di chuyển',
    requestArrival: 'Yêu cầu khách xác nhận đã đến',
    startDiagnosis: 'Bắt đầu kiểm tra xe',
    createQuote: 'Tạo báo giá',
    workDescription: 'Nội dung công việc',
    amount: 'Số tiền (VND)',
    repairBike: 'Sửa xe',
    transportBike: 'Chở xe',
    sendQuote: 'Gửi báo giá cho khách',
    startRepair: 'Bắt đầu sửa tại chỗ',
    switchTransport: 'Chuyển sang chở xe',
    startApprovedRepair: 'Bắt đầu công việc sửa xe đã duyệt',
    startApprovedTransport: 'Bắt đầu vận chuyển đã duyệt',
    requestCompletion: 'Yêu cầu khách xác nhận hoàn tất',
    reasonRequired: 'Hãy nhập lý do cụ thể để lưu vào audit.',
    cancelError: 'Không thể hủy ca.',
    cannotContinue: 'báo không thể tiếp tục',
    auditCancel: 'Dừng ca có audit',
    auditBody:
      'Chỉ dùng khi có sự cố an toàn hoặc không thể tiếp tục. Hệ thống sẽ thông báo cho bên còn lại.',
    withdrawBody:
      'Hệ thống sẽ giữ nguyên yêu cầu của khách và tìm đội khác. Nếu công việc đã bắt đầu, ca được chuyển cho điều phối viên xử lý.',
    reason: 'Lý do',
    confirmCancel: 'Xác nhận dừng ca',
    keep: 'Giữ ca',
    saveReviewError: 'Không thể lưu đánh giá',
    retryGeneric: 'Vui lòng thử lại.',
    deleteReviewTitle: 'Xóa đánh giá?',
    deleteReviewBody: 'Bạn có thể tạo đánh giá mới sau đó.',
    deleteReviewError: 'Không thể xóa đánh giá',
    editReview: 'Chỉnh sửa đánh giá',
    review: 'Đánh giá ca cứu hộ',
    reviewPlaceholder: 'Nhận xét về thái độ và chất lượng xử lý',
    saveReview: 'Lưu đánh giá',
    deleteReview: 'Xóa đánh giá',
    incidentTitle: 'Khiếu nại hoặc báo sự cố',
    incidentIntro: 'Nội dung này tách biệt với đánh giá sao và chỉ khách, điều phối viên, admin được xem.',
    reportIncident: 'Gửi khiếu nại / báo sự cố',
    incidentCategory: 'Nhóm vấn đề',
    incidentDescription: 'Mô tả sự việc',
    incidentPlaceholder: 'Nêu diễn biến cụ thể, tránh ghi thông tin cá nhân không cần thiết',
    incidentRequired: 'Hãy chọn nhóm và nhập mô tả ít nhất 10 ký tự.',
    incidentSent: 'Đã gửi để điều phối viên kiểm tra.',
    incidentError: 'Không thể gửi nội dung này.',
    incidentResolution: 'Kết quả xử lý',
    resolveIncident: 'Xác nhận đã xử lý',
    dismissIncident: 'Bác bỏ có lý do',
    incidentStatuses: { open: 'Đang xử lý', resolved: 'Đã xử lý', dismissed: 'Đã bác bỏ' },
    incidentCategories: {
      provider_conduct: 'Thái độ cứu hộ viên',
      service_quality: 'Chất lượng dịch vụ',
      safety: 'Vấn đề an toàn',
      property_damage: 'Hư hại tài sản',
      other: 'Vấn đề khác',
    },
  },
  en: {
    retryError: 'Could not find another rescue team.',
    loadError: 'Could not load this request.',
    back: 'Go back',
    pickupMarker: 'Rescue location',
    destinationMarker: 'Motorcycle drop-off',
    provider: 'Rescue provider',
    contact: 'Contact',
    roadRoute: 'Motorcycle road route',
    noRoute: 'Route unavailable',
    landmark: 'Landmark',
    destination: 'Drop-off point',
    team: 'Verified team',
    vehicle: 'Identification vehicle',
    initialEta: 'Initial ETA',
    aboutMinutes: 'About {value} min',
    road: 'Road distance',
    fullscreen: 'Open full-screen map',
    routingWarning:
      'The routing service did not return a valid route. The app never substitutes a straight line; dispatch staff should retry when routing is available.',
    noProviderTitle: 'No team has accepted yet',
    noProviderBody:
      'The search has stopped instead of waiting forever. Contact dispatch if you need another option.',
    callDispatch: 'Call dispatch',
    requestDispatchSupport: 'Request dispatch support',
    supportRequested: 'Request sent. A dispatcher will review this case.',
    supportError: 'Could not request dispatch support.',
    dispatcher: 'Dispatcher',
    retry: 'Find another suitable team',
    gpsStaleTitle: 'Provider location is stale',
    gpsStaleBody: 'Route and ETA are paused until the provider device sends a fresh GPS point.',
    dispatchRequiredTitle: 'Dispatch is handling this request',
    dispatchRequiredBody:
      'The previous provider could not continue. Your request remains open and is not cancelled.',
    attentionRequired: 'This request has an operational alert that needs review',
    progress: 'Progress',
    callProvider: 'Call rescue provider at',
    contactLabel: 'Contact number for this request',
    contactPrivacy: 'Work number verified by the operator',
    call: 'Call',
    tracking: {
      idle: 'Location tracking is not active.',
      requesting: 'Requesting location permission…',
      tracking: "Sharing location with this request's customer.",
      denied: 'Location permission is missing; you cannot handle the request safely.',
      error: 'Location connection lost. The system will retry after the next GPS update.',
    },
    expoTracking: 'Expo Go only tracks while this screen is open.',
    quote: 'Quote',
    transport: 'Motorcycle transport',
    repair: 'Repair',
    quotePending: 'Pending',
    quoteApproved: 'Approved',
    quoteRejected: 'Rejected',
    quoteSuperseded: 'Superseded',
    actionError: 'Could not complete the action.',
    cancelTitle: 'Cancel request?',
    cancelBody: 'Choose a reason so dispatch can understand the situation. This action is recorded.',
    no: 'No',
    cancel: 'Cancel request',
    chooseCancelReason: 'Cancellation reason',
    cancelReasonRequired: 'Choose a cancellation reason.',
    otherReasonRequired: 'Describe the reason using at least 5 characters.',
    cancelNote: 'Additional details (optional)',
    cancelOtherNote: 'Describe the reason',
    lateCancelWarning:
      'The rescue provider has departed. This will be recorded as a late cancellation; repeated late cancellations may temporarily limit new requests.',
    arrivalDisputeWarning:
      'The provider reported arriving. If you cannot see them, this cancellation will be flagged for dispatch review.',
    cancelAfterArrivalTitle: 'Need to stop after confirming provider arrival?',
    cancelAfterArrivalBody:
      'Self-cancellation is disabled while work is in progress. Call dispatch so both parties are protected and the request history stays accurate.',
    cancellationRecorded: 'Cancellation details',
    operationalCancellation: 'The request was stopped by the rescue provider or dispatch staff.',
    lateCancellationRecorded: 'Late cancellation recorded',
    gpsNearRecorded: 'GPS was near the rescue point at cancellation',
    reasonLabels: {
      issue_resolved: 'The motorcycle works again / help is no longer needed',
      changed_mind: 'Changed mind or chose another option',
      wrong_location: 'Incorrect pickup location',
      duplicate_request: 'Duplicate request',
      provider_not_present: 'Provider is not visible at the meeting point',
      provider_unavailable: 'Provider could not continue',
      safety_issue: 'Safety issue',
      customer_unreachable: 'Customer could not be reached',
      duplicate_or_fraud: 'Duplicate or suspicious request',
      other: 'Other reason',
    },
    confirmArrival: 'Confirm provider arrival',
    rejectArrival: 'Provider not here',
    approveQuote: 'Approve quote',
    rejectQuote: 'Reject quote',
    chooseDestination: 'Choose drop-off point',
    destinationBeforeQuote: 'A transport quote needs a drop-off point before you can approve it.',
    confirmCompletion: 'Confirm completion',
    incomplete: 'Work is not complete',
    feedbackTitle: 'Tell us what is wrong',
    feedbackReasonRequired: 'Choose a reason before submitting.',
    feedbackNote: 'Additional details',
    sendFeedback: 'Submit and request correction',
    closeFeedback: 'Go back',
    feedbackReasons: {
      provider_not_visible: 'Provider is not visible at the meeting point',
      wrong_meeting_point: 'Provider is at the wrong point',
      cannot_contact_provider: 'Provider cannot be contacted',
      issue_persists: 'The motorcycle issue remains',
      work_not_as_agreed: 'Work does not match what was agreed',
      destination_not_reached: 'Motorcycle has not reached the drop-off',
      other: 'Other reason',
    },
    stateError: 'Could not update request status.',
    quoteInvalid: 'Enter a valid work description and quote amount.',
    quoteError: 'Could not send the quote.',
    startTrip: 'Start trip',
    requestArrival: 'Ask customer to confirm arrival',
    startDiagnosis: 'Start motorcycle inspection',
    createQuote: 'Create quote',
    workDescription: 'Work description',
    amount: 'Amount (VND)',
    repairBike: 'Repair',
    transportBike: 'Transport',
    sendQuote: 'Send quote to customer',
    startRepair: 'Start on-site repair',
    switchTransport: 'Switch to transport',
    startApprovedRepair: 'Start approved repair',
    startApprovedTransport: 'Start approved transport',
    requestCompletion: 'Ask customer to confirm completion',
    reasonRequired: 'Enter a specific reason for the audit record.',
    cancelError: 'Could not cancel the request.',
    cannotContinue: 'cannot continue',
    auditCancel: 'Audited request stop',
    auditBody:
      'Use only for a safety issue or when work cannot continue. The other participant will be notified.',
    withdrawBody:
      'The customer request stays open and another team will be searched. If work already began, dispatch will take over.',
    reason: 'Reason',
    confirmCancel: 'Confirm request stop',
    keep: 'Keep request',
    saveReviewError: 'Could not save review',
    retryGeneric: 'Please try again.',
    deleteReviewTitle: 'Delete review?',
    deleteReviewBody: 'You can create another review later.',
    deleteReviewError: 'Could not delete review',
    editReview: 'Edit review',
    review: 'Review rescue request',
    reviewPlaceholder: 'Comment on attitude and service quality',
    saveReview: 'Save review',
    deleteReview: 'Delete review',
    incidentTitle: 'Complaint or incident report',
    incidentIntro: 'This is separate from star ratings and is visible only to you, dispatchers, and admins.',
    reportIncident: 'Submit complaint / incident',
    incidentCategory: 'Issue category',
    incidentDescription: 'What happened',
    incidentPlaceholder: 'Describe concrete events without unnecessary personal information',
    incidentRequired: 'Choose a category and enter at least 10 characters.',
    incidentSent: 'Submitted for dispatch review.',
    incidentError: 'Could not submit this report.',
    incidentResolution: 'Resolution result',
    resolveIncident: 'Mark as resolved',
    dismissIncident: 'Dismiss with reason',
    incidentStatuses: { open: 'In review', resolved: 'Resolved', dismissed: 'Dismissed' },
    incidentCategories: {
      provider_conduct: 'Provider conduct',
      service_quality: 'Service quality',
      safety: 'Safety concern',
      property_damage: 'Property damage',
      other: 'Other issue',
    },
  },
} as const;

export function useRescueDetailsCopy() {
  return useCopy(RESCUE_DETAILS_COPY);
}
