import { StyleSheet } from 'react-native';
import { Colors } from '@/src/constants/colors';
import { Fonts, Radius, Spacing, Typography } from '@/src/constants/spacing';

export const rescueDetailsStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.background },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.lg,
    backgroundColor: Colors.background,
    gap: Spacing.md,
  },
  mapWrap: { height: '40%', minHeight: 280, backgroundColor: Colors.surface },
  statusScrim: { position: 'absolute', top: 0, left: 0, right: 0, backgroundColor: Colors.mapScrim },
  back: {
    position: 'absolute',
    left: Spacing.md,
    width: 44,
    height: 44,
    borderRadius: Radius.lg,
    backgroundColor: Colors.glass,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapBadge: {
    position: 'absolute',
    right: Spacing.md,
    minHeight: 40,
    paddingHorizontal: Spacing.md,
    borderRadius: Radius.md,
    backgroundColor: Colors.glass,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  liveDot: { width: 8, height: 8, borderRadius: Radius.full },
  mapBadgeText: { ...Typography.caption, color: Colors.textPrimary },
  sheet: {
    flex: 1,
    marginTop: -18,
    borderTopLeftRadius: Radius.xl,
    borderTopRightRadius: Radius.xl,
    backgroundColor: Colors.background,
  },
  content: { padding: Spacing.lg, gap: Spacing.md },
  statusRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  statusIcon: {
    width: 52,
    height: 52,
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  service: { ...Typography.h2, color: Colors.textPrimary },
  status: { ...Typography.bodyBold },
  infoCard: {
    padding: Spacing.md,
    borderRadius: Radius.lg,
    backgroundColor: Colors.cardBg,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: Spacing.md,
  },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  infoLabel: { ...Typography.caption, color: Colors.textMuted },
  infoValue: { ...Typography.bodyBold, color: Colors.textPrimary },
  contactPrivacy: { ...Typography.caption, color: Colors.textSecondary },
  callChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: Radius.md,
    backgroundColor: Colors.accentSoft,
  },
  callChipText: { ...Typography.caption, color: Colors.primaryDark, fontFamily: Fonts.bodySemi },
  warning: { padding: Spacing.md, borderRadius: Radius.md, backgroundColor: Colors.warningSoft },
  warningText: { ...Typography.caption, color: Colors.warning },
  tracking: {
    flexDirection: 'row',
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.md,
    backgroundColor: Colors.sky,
  },
  trackingText: { ...Typography.caption, color: Colors.textSecondary, flex: 1 },
  noProviderCard: {
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.lg,
    backgroundColor: Colors.cardBg,
    borderWidth: 1,
    borderColor: Colors.warning,
  },
  noProviderTitle: { ...Typography.bodyBold, color: Colors.textPrimary },
  quoteCard: {
    padding: Spacing.lg,
    borderRadius: Radius.lg,
    backgroundColor: Colors.accentSoft,
    borderWidth: 1,
    borderColor: Colors.accent,
  },
  quoteDescription: { ...Typography.body, color: Colors.textPrimary, marginTop: Spacing.sm },
  quoteAmount: { ...Typography.h2, color: Colors.primaryDark, marginVertical: Spacing.sm },
  actions: { gap: Spacing.sm },
  destinationRequiredCard: {
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.lg,
    backgroundColor: Colors.warningSoft,
    borderWidth: 1,
    borderColor: Colors.warning,
  },
  feedbackPanel: {
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.warning,
    backgroundColor: Colors.warningSoft,
  },
  section: { ...Typography.h3, color: Colors.textPrimary },
  timeline: { padding: Spacing.md, borderRadius: Radius.lg, backgroundColor: Colors.cardBg },
  event: { flexDirection: 'row', minHeight: 58 },
  eventRail: { width: 24, alignItems: 'center' },
  eventDot: {
    width: 12,
    height: 12,
    borderRadius: Radius.full,
    backgroundColor: Colors.primary,
    marginTop: 5,
  },
  eventLine: { width: 2, flex: 1, backgroundColor: Colors.divider },
  eventBody: { flex: 1, paddingBottom: Spacing.md },
  eventTitle: { ...Typography.bodyBold, color: Colors.textPrimary },
  eventTime: { ...Typography.caption, color: Colors.textMuted },
  quoteForm: {
    padding: Spacing.md,
    borderRadius: Radius.lg,
    backgroundColor: Colors.cardBg,
    gap: Spacing.sm,
  },
  workRow: { flexDirection: 'row', gap: Spacing.sm },
  workChip: {
    flex: 1,
    alignItems: 'center',
    padding: 12,
    borderRadius: Radius.md,
    backgroundColor: Colors.surface,
  },
  workChipActive: { backgroundColor: Colors.accent },
  workText: { ...Typography.bodyBold, color: Colors.textPrimary },
  reviewCard: {
    padding: Spacing.lg,
    borderRadius: Radius.lg,
    backgroundColor: Colors.cardBg,
    gap: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.accent,
  },
  incidentPanel: {
    padding: Spacing.md,
    gap: Spacing.sm,
    borderRadius: Radius.lg,
    backgroundColor: Colors.cardBg,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  incidentCard: {
    padding: Spacing.md,
    gap: Spacing.xs,
    borderRadius: Radius.md,
    backgroundColor: Colors.surface,
  },
  incidentStatus: { ...Typography.caption, color: Colors.primary, fontFamily: Fonts.bodySemi },
  stars: { flexDirection: 'row', gap: Spacing.sm },
  starButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  error: { ...Typography.body, color: Colors.error },
  smallButton: { maxWidth: 220 },
  flex: { flex: 1 },
  cancellationSummary: {
    padding: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.cardBg,
    gap: Spacing.sm,
  },
  summaryTitleRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  lateCancellationText: { ...Typography.bodyBold, color: Colors.warning },
  fieldLabel: { ...Typography.bodyBold, color: Colors.textPrimary },
  reasonList: { gap: Spacing.sm },
  reasonOption: {
    minHeight: 48,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    backgroundColor: Colors.background,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  reasonOptionSelected: { borderColor: Colors.primary, backgroundColor: Colors.sky },
  reasonOptionText: { ...Typography.body, color: Colors.textPrimary, flex: 1 },
  cancelWarning: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.md,
    backgroundColor: Colors.warningSoft,
  },
  cancelWarningText: { ...Typography.caption, color: Colors.warning, flex: 1 },
  assistedCancelCard: {
    padding: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.warning,
    backgroundColor: Colors.warningSoft,
    gap: Spacing.sm,
  },
  cancelPanel: {
    padding: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.error,
    backgroundColor: Colors.errorSubtle,
    gap: Spacing.sm,
  },
});
